markdown:         redcarpet
title:            cworks
tagline:          'Dream and Do'
description:      'Dream and Do'
url:              http://corbettworks.net
baseurl:          /

author:
  name:           'Corbett'
  url:            http://localhost:4000

version:          1.0.1

github:
  repo:           https://github.com/cworks

linkedin:
  url:            https://www.linkedin.com/in/corbettmartin

facebook:
  url:            https://www.facebook.com/corbett.martin.9

instagram:
  url:            http://instagram.com/corbettworks

flickr:
  url:            https://www.flickr.com/photos/130419749@N03

permalink: /blog/:year/:month/:day/:title/
paginate: 5            # Posts per page on the blog index
pagination_dir: blog/page/:num  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5        # Posts in the sidebar Recent Posts section
titlecase: true        # Converts page and post titles to titlecase
category_dir: categories

gems:
  - jekyll-archives
  - stringex
